### ISSUE TITLE
Some issues in 'make' when using with legato-17.08.1

### ISSUE THREAD

**Issue by wedapashi** [startwithsierra/mangoh-to-gcloud#1]
I understand that this was tested with legato-17.06 version.
I am trying to use this same example with 17.08.1 version.

1. In sensorToGoogleCloud.cc file a `json_ptr` is missing its definition, not sure why it is required.

2. In sensorToGoogleCloud.cc file a `json_pack` is missing its definition.

3. Expects a primary-expression before '.' in `this->_jwt = JWT::Encode(&signer, json.get());`

**Comment by wedapashi** [comment]
Sorry, that wasn't about this project, but about jwt library requirement. It could indeed help if it specifies what libraries it is compatible with.

**Comment by majdi** [comment]
Sure, thanks for the details around jwt library. I'll add this asap.

**Comment by wedapashi** [comment]
@majdi Is there an update? I am facing some issues with cross-compiling libraries like jwt, jansson, openssl, which are required for this project to build.

**Comment by majdi** [comment]
Hello @WedaPashi10,
I'm actually working on a new version without all JWT dependencies.
I'll push this last update asap

**Comment by wedapashi** [comment]
Hi Majdi, is there an update on newer version which doesn't depend on jwt-cpp?

**Comment by wedapashi** [comment]
Hi Majdi, is there an update on newer version which doesn't depend on jwt-cpp?

**Comment by majdi** [comment]
Hi @WedaPashi10, sure, I'm replacing the jwt-cpp library with a home-made specific jwt generator with no dependence.

**Comment by wedapashi** [comment]
Hi @majdi is there an update on newer version?
